export enum EstadoAjuste {
    EN_PROCESO = 'EN_PROCESO',
    PENDIENTE_APROBACION = 'PENDIENTE_APROBACION',
    ENVIADO_APROBACION = 'ENVIADO_APROBACION',
    APROBADO = 'APROBADO',
    RECHAZADO = 'RECHAZADO',
}