export enum TipoDatoCampo {
    NUMERO = 'NUMERO',
    TEXTO = 'TEXTO',
    BOOLEANO = 'BOOLEANO',
    FECHA = 'FECHA',
    HORA = 'HORA',
    CORREO_ELECTRONICO = 'CORREO_ELECTRONICO',
    LISTA_VALORES_TEXTO = 'LISTA_VALORES_TEXTO'
}
